min_version = "2025.7.0"

[tools]
bun = "latest"
elixir = "latest"
erlang = "latest"
"github:wilsonzlin/minify-html" = { version = "latest", bin = "minify-html" }
hk = "latest"
"npm:prettier" = "latest"
pkl = "latest"

[settings]
experimental = true
lockfile = true

[settings.npm]
bun = true
