name: Deploy site to GH pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jdx/rtx-action@v1
      - name: Elixir Deps Cache
        id: elixir-deps-cache
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
            .mix/archives/
          key: elixir-build-${{hashFiles('.rtx.toml')}}-${{hashFiles('mix.lock')}}
          restore-keys: elixir-build-${{hashFiles('.rtx.toml')}}-
      - name: Install Elixir Dependencies
        run: |
          mix local.hex --force --if-missing
          mix deps.get
      - name: Yarn Deps Cache
        id: yarn-deps-cache
        uses: actions/cache@v3
        with:
          path: |
            assets/node_modules
          key: node-build-${{hashFiles('.rtx.toml')}}-${{hashFiles('assets/yarn.lock')}}
          restore-keys: node-build-${{hashFiles('.rtx.toml')}}-
      - name: Install node Dependencies
        working-directory: assets/
        run: |
          yarn
      - name: "Build Tableau"
        env:
          # Needed for building MDEX from my fork
          # Remove when tomorrow themes are merged
          MDEX_BUILD: 1
          MIX_ENV: prod
        run: |
          mix tableau.build
      - name: "Build static assets"
        working-directory: assets/
        env:
          NODE_ENV: "production"
        run: |
          yarn build
      - name: Shrink HTML
        run: |
          curl https://wilsonl.in/minify-html/bin/0.11.1-linux-x86_64 > minify
          chmod +x minify
          shopt -s globstar
          ./minify --minify-css --minify-js _site/**/*.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v1
